# Generated by Django 6.0.3 on 2026-03-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='Device name')),
                ('mac_address', models.CharField(max_length=31, unique=True, verbose_name='Mac address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('voltage', models.DecimalField(decimal_places=2, help_text='Voltage in [v]', max_digits=5, verbose_name='Voltage')),
                ('current', models.DecimalField(decimal_places=4, help_text='Current in [A]', max_digits=7, verbose_name='Current[mA]')),
                ('power', models.DecimalField(blank=True, decimal_places=3, help_text='Power in [W]', max_digits=6, verbose_name='Power')),
                ('battery_level', models.IntegerField()),
                ('tracker_angle_x', models.IntegerField(blank=True, null=True, verbose_name='Tracker angle horizontal')),
                ('tracker_angle_y', models.IntegerField(blank=True, null=True, verbose_name='Tracker angle vertical')),
            ],
            options={
                'verbose_name': 'Telemetry',
                'verbose_name_plural': 'Telemetries',
            },
        ),
    ]
